ImageId: 'ami-0bb4c991fa89d4b9b'
MinCount: 1
MaxCount: 1
InstanceType: 't2.micro'
KeyName: 'l00157158_key_pair'
Tags:
  - Key: 'Name'
    Value: 'MyDemoInstance'
  - Key: 'Environment'
    Value: 'Dev'
