AWSTemplateFormatVersion: 2010-09-09
Resources:  
  # Define the security group for MySQL
  FHIITMySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !Ref FHIITVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupId: !GetAtt FHIITSubNetPvtSecurityGroup.GroupId
