AWSTemplateFormatVersion: 2010-09-09
Description: Master CloudFormation template to orchestrate all sub-modules

Resources:
  ParametersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITParameters.yml

  FHIITNetworkInfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITNetworkInfra.yml


  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITEc2Sg.yml

  EC2InstancesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITEC2Instances.yml
  
  RDSSecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITRDSsg.yml

  RDSDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIITRDSInstances.yml

Outputs:
  VPCId:
    Value: !GetAtt FHIITNetworkInfra.Outputs.VPCId
  ElasticIP:
    Value: !GetAtt FHIITNetworkInfra.Outputs.ElasticIP
  PubSubnetID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PubSubnetID
  PvtSubNet2ID: 
    Value: !GetAtt FHIITNetworkInfra.Outputs.PvtSubNet2ID
  SQLSubnetID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.SQLSubnetID
  InternetGatewayId:
    Value: !GetAtt FHIITNetworkInfra.Outputs.InternetGatewayId
  AttachGateWayID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.AttachGateWayID
  PublicRouteTableID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PublicRouteTableID
  PrivateRouteTableID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PrivateRouteTableID
  PrivateRouteId:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PrivateRouteId
  PvtSubnet1RouteTableAssociationID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PvtSubnet1RouteTableAssociationID
  PvtSubnet21RouteTableAssociationID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PvtSubnet21RouteTableAssociationID
  PublictRouteID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PublictRouteID
  PubSubnetRouteTableAssociationID:
    Value: !GetAtt FHIITNetworkInfra.Outputs.PubSubnetRouteTableAssociationID