AWSTemplateFormatVersion: 2010-09-09
Description: Master CloudFormation template to orchestrate all sub-modules

Resources:
  ParametersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-Parameters.yml

  NFHIIT-Network-Infra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-Network-Infra.yml


  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-Ec2-Sg.yml

  EC2InstancesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-EC2-Instances.yml
  
  RDSSecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-RDS-sg.yml

  RDSDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://fhiit-cloudformation.s3.eu-west-1.amazonaws.com/FHIIT-RDS-Instances.yml

Outputs:
  VPCId:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.VPCId
  ElasticIP:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.ElasticIP
  PubSubnetID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PubSubnetID
  PvtSubNet1ID: 
   Value: !GetAtt FHIIT-Network-Infra.Outputs.PvtSubNet1ID
  PvtSubNet2ID: 
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PvtSubNet2ID
  SQLSubnetID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.SQLSubnetID
  InternetGatewayId:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.InternetGatewayId
  AttachGateWayID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.AttachGateWayID
  PublicRouteTableID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PublicRouteTableID
  PrivateRouteTableID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PrivateRouteTableID
  PrivateRouteId:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PrivateRouteId
  PvtSubnet1RouteTableAssociationID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PvtSubnet1RouteTableAssociationID
  PvtSubnet21RouteTableAssociationID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PvtSubnet21RouteTableAssociationID
  PublictRouteID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PublictRouteID
  PubSubnetRouteTableAssociationID:
    Value: !GetAtt FHIIT-Network-Infra.Outputs.PubSubnetRouteTableAssociationID